name: Update Installer Scripts

on:
  release:
    types: [published]

jobs:
  update-installers:
    name: Update Installer Scripts
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Get version from tag
        id: version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          VERSION=${VERSION#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Update install.sh
        run: |
          sed -i "s/VERSION=\"[^\"]*\"/VERSION=\"${{ steps.version.outputs.version }}\"/" scripts/install.sh

      - name: Update install.ps1
        run: |
          sed -i "s/\[string\]\$Version = \"[^\"]*\"/[string]\$Version = \"${{ steps.version.outputs.version }}\"/" scripts/install.ps1

      - name: Update Homebrew formula
        run: |
          sed -i "s/version \"[^\"]*\"/version \"${{ steps.version.outputs.version }}\"/" Formula/twig.rb
          sed -i "s/download\/v[^\/]*\//download\/v${{ steps.version.outputs.version }}\//g" Formula/twig.rb

      - name: Update Chocolatey package
        run: |
          sed -i "s/<version>[^<]*<\/version>/<version>${{ steps.version.outputs.version }}<\/version>/" chocolatey/twig.nuspec
          sed -i "s/download\/v[^\/]*\//download\/v${{ steps.version.outputs.version }}\//g" chocolatey/tools/chocolateyinstall.ps1

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add scripts/install.sh scripts/install.ps1 Formula/twig.rb chocolatey/twig.nuspec chocolatey/tools/chocolateyinstall.ps1
          git commit -m "chore: update installer scripts to v${{ steps.version.outputs.version }}" || echo "No changes to commit"
          git push origin main 